# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, inputs, ... }:

{
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/8b3b54f8-35d0-4661-9da9-b36035a42d65";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/12D2-6135";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/8d38cd5c-42f5-4dfc-b95a-2125eec46836"; }
    ];
}
